### ISSUE TITLE
stdlib + puppet: no implicit conversion of nil into String (app_management)

### ISSUE THREAD

**Issue by domcleal** [puppet-testing/puppet-tester#2]
<pre>
  1) deprecation should display a single warning
     Failure/Error: is_expected.to run.with_params('key', 'heelo')
     
     TypeError:
       no implicit conversion of nil into String
     # ./vendor/bundle/ruby/2.1.0/gems/rspec-puppet-2.5.0/lib/rspec-puppet/support.rb:180:in `directory?'
     # ./vendor/bundle/ruby/2.1.0/gems/rspec-puppet-2.5.0/lib/rspec-puppet/support.rb:180:in `ensure in with_vardir'
     # ./vendor/bundle/ruby/2.1.0/gems/rspec-puppet-2.5.0/lib/rspec-puppet/support.rb:180:in `with_vardir'
     # ./vendor/bundle/ruby/2.1.0/gems/rspec-puppet-2.5.0/lib/rspec-puppet/example/function_example_group.rb:67:in `find_function'
     # ./vendor/bundle/ruby/2.1.0/gems/rspec-puppet-2.5.0/lib/rspec-puppet/example/function_example_group.rb:61:in `subject'
     # ./spec/functions/deprecation_spec.rb:15:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Mocha::ExpectationError:
     #   unexpected invocation: Puppet.warning('Modifying 'app_management' as a setting is deprecated.\n   (at /home/travis/build/puppet-testing/puppetlabs-stdlib/vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/settings.rb:1144:in `issue_deprecation_warning')')
     #   unsatisfied expectations:
     #   - expected exactly once, not yet invoked: Puppet.warning(includes('heelo'))
     #   satisfied expectations:
     #   - allowed any number of times, not yet invoked: #<Puppet::Util::Feature:0x2849318>.root?(any_parameters)
     #   ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/util/logging.rb:285:in `issue_deprecation_warning'</pre>

https://travis-ci.org/puppet-testing/puppetlabs-stdlib/jobs/197952496

Looks like modifying app_management (now a deprecated and useless setting on Puppet#master) is causing a mocha expectation to fail, which then triggers the unrelated implicit conversion error in an `ensure` clause.

**Comment by domcleal** [comment]
Fixed by https://github.com/rodjek/rspec-puppet/pull/454.
