### ISSUE TITLE
stdlib + Puppet: loadjson/load_module_metadata

### ISSUE THREAD

**Issue by domcleal** [puppet-testing/puppet-tester#3]
<pre>
  8) loadjson when calling with valid arguments when a non-existing file is specified 
     Failure/Error: it { is_expected.to run.with_params(filename, {'default' => 'value'}).and_return({'default' => 'value'}) }
     
       #<File (class)> received :read with unexpected arguments
         expected: (/\/stdlib\/metadata.json/)
              got: ("/home/travis/build/puppet-testing/puppetlabs-stdlib/spec/fixtures/modules/test/metadata.json", {:encoding=>"utf-8"})
       Diff:
       @@ -1,2 +1,3 @@
       -[/\/stdlib\/metadata.json/]
       +["/home/travis/build/puppet-testing/puppetlabs-stdlib/spec/fixtures/modules/test/metadata.json",
       + {:encoding=>"utf-8"}]
       
        Please stub a default value first if message might be received with other args as well. 
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/module.rb:143:in `read_metadata'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/module.rb:160:in `load_metadata'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/module.rb:68:in `initialize'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/node/environment.rb:316:in `new'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/node/environment.rb:316:in `block in modules'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/node/environment.rb:314:in `collect'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/node/environment.rb:314:in `modules'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/pops/loaders.rb:286:in `configure_loaders_for_modules'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/pops/loaders.rb:267:in `create_environment_loader'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/pops/loaders.rb:53:in `initialize'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/pops/loaders.rb:24:in `new'
     # ./vendor/bundle/ruby/2.1.0/gems/rspec-puppet-2.5.0/lib/rspec-puppet/example/function_example_group.rb:74:in `block (2 levels) in find_function'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet/context.rb:65:in `override'
     # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-71b8c9009ef7/lib/puppet.rb:293:in `override'
     # ./vendor/bundle/ruby/2.1.0/gems/rspec-puppet-2.5.0/lib/rspec-puppet/example/function_example_group.rb:73:in `block in find_function'
     # ./vendor/bundle/ruby/2.1.0/gems/rspec-puppet-2.5.0/lib/rspec-puppet/support.rb:178:in `with_vardir'
     # ./vendor/bundle/ruby/2.1.0/gems/rspec-puppet-2.5.0/lib/rspec-puppet/example/function_example_group.rb:67:in `find_function'
     # ./vendor/bundle/ruby/2.1.0/gems/rspec-puppet-2.5.0/lib/rspec-puppet/example/function_example_group.rb:61:in `subject'
     # ./spec/functions/loadjson_spec.rb:25:in `block (4 levels) in <top (required)>'
</pre>

etc.

https://travis-ci.org/puppet-testing/puppetlabs-stdlib/builds/197952494

**Comment by domcleal** [comment]
Caused by puppetlabs/puppet@f2e8e664 (https://tickets.puppetlabs.com/browse/PUP-5027, 5.0.0).

**Comment by domcleal** [comment]
Fixed by https://github.com/puppetlabs/puppetlabs-stdlib/pull/719.
