### ISSUE TITLE
puppet-syntax + Puppet: "Found 2 errors. Giving up" message change, PUP-6006

### ISSUE THREAD

**Issue by domcleal** [puppet-testing/puppet-tester#4]
<pre>
  1) PuppetSyntax::Manifests should return an error from an invalid file
     Failure/Error: expect(output[2]).to match(/Found 2 errors. Giving up/)
     
       expected "Language validation logged 2 errors. Giving up" to match /Found 2 errors. Giving up/
       Diff:
       @@ -1,2 +1,2 @@
       -/Found 2 errors. Giving up/
       +"Language validation logged 2 errors. Giving up"
       
     # ./spec/puppet-syntax/manifests_spec.rb:33:in `block (2 levels) in <top (required)>'

  2) PuppetSyntax::Manifests should continue after finding an error in the first file
     Failure/Error: expect(output[2]).to match('Found 2 errors. Giving up')
       expected "Language validation logged 2 errors. Giving up" to match "Found 2 errors. Giving up"
     # ./spec/puppet-syntax/manifests_spec.rb:79:in `block (2 levels) in <top (required)>'
</pre>

https://travis-ci.org/puppet-testing/puppet-syntax/builds/197925148

The message changed slightly in https://github.com/puppetlabs/puppet/commit/efcdf58, only affects tests.

**Comment by domcleal** [comment]
https://github.com/voxpupuli/puppet-syntax/pull/72
