### ISSUE TITLE
puppet-syntax + Puppet: app_management failures

### ISSUE THREAD

**Issue by domcleal** [puppet-testing/puppet-tester#5]
<pre>

  3) PuppetSyntax::Manifests app_management app_management = false (default) should fail to parse an application manifest
     Failure/Error: expect(has_errors).to eq(true)
     
       expected: true
            got: false
     
       (compared using ==)
     # ./spec/puppet-syntax/manifests_spec.rb:150:in `block (4 levels) in <top (required)>'

  4) PuppetSyntax::Manifests app_management app_management = true should successfully parse an application manifest on Puppet >= 4.3.0
     Failure/Error: expect(output.size).to eq(0)
     
       expected: 0
            got: 1
     
       (compared using ==)
     # ./spec/puppet-syntax/manifests_spec.rb:165:in `block (4 levels) in <top (required)>'</pre>

https://travis-ci.org/puppet-testing/puppet-syntax/builds/197925148

Most likely as the app_management setting is now deprecated and on by default in Puppet#master.

**Comment by domcleal** [comment]
https://github.com/voxpupuli/puppet-syntax/pull/72
